# Generated by Django 5.1.7 on 2025-03-18 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="description",
            new_name="emailAdress",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="price",
            new_name="phoneNumber",
        ),
    ]
